# Generated by Django 6.1.1 on 2026-09-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Hostname / Device Name')),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('host', 'Host'), ('nmas', 'NMAS Station'), ('server', 'Internet Web Server'), ('backup', 'Backup Node')], default='router', max_length=32)),
                ('vendor', models.CharField(choices=[('arista', 'Arista cEOS'), ('cisco_nxos', 'Cisco NX-OS 9000v'), ('cisco_xrv', 'Cisco IOS-XRv 9000'), ('sonic', 'SONiC VS (sonic-vs)'), ('linux', 'Linux Host / Server')], default='arista', max_length=64)),
                ('tier', models.CharField(choices=[('distribution', 'Tier 1: Distribution Routers (R1-R2)'), ('asbr', 'Tier 2: ASBR Core Routers (R3-R4)'), ('pe_router', 'Tier 3: PE WAN Gateway (R5)'), ('access_switch', 'Tier 4: Access Switches (S1-S2)'), ('core_switch', 'Tier 5: Core Backbone Switches (S3-S4)'), ('host', 'End Host (H1-H4)'), ('management', 'Management & Automation')], default='distribution', max_length=64)),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Deployment Role')),
                ('public_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='Public / WAN IP')),
                ('private_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='Private IP')),
                ('mgmt_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='Management IP')),
                ('status', models.CharField(default='Online', max_length=32)),
                ('routing_protocols', models.CharField(blank=True, default='OSPF', max_length=128, verbose_name='Routing Protocol(s)')),
                ('bgp_asn', models.IntegerField(blank=True, null=True, verbose_name='BGP Local ASN')),
                ('router_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Router ID')),
                ('interface_ips', models.TextField(blank=True, verbose_name='Interface IPs / Descriptions')),
                ('vlans', models.CharField(blank=True, max_length=128, verbose_name='VLANs (e.g. 10,20,30)')),
                ('custom_config_yaml', models.TextField(blank=True, verbose_name='YAML Data Model')),
                ('running_config', models.TextField(blank=True, verbose_name='Live Running Configuration')),
                ('template_name', models.CharField(blank=True, default='r1_r2.j2', max_length=128, verbose_name='Jinja2 Template File')),
                ('uploaded_config_file', models.FileField(blank=True, null=True, upload_to='uploaded_configs/', verbose_name='Uploaded Running Config File')),
                ('uploaded_template_file', models.FileField(blank=True, null=True, upload_to='uploaded_templates/', verbose_name='Uploaded Jinja2 Template File')),
                ('last_config_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('vendor', models.CharField(max_length=64)),
                ('tier', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor', 'tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoldenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_tag', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('config_content', models.TextField()),
                ('change_summary', models.CharField(default='Baseline Golden Config Snapshot', max_length=255)),
                ('created_by', models.CharField(default='Network Automation Engine', max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_configs', to='automation.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
