# Generated by Django 6.1.1 on 2026-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=128)),
                ('target_device', models.CharField(max_length=64)),
                ('api_endpoint', models.CharField(default='http://<mgmt_ip>/command-api', max_length=128)),
                ('api_command', models.TextField()),
                ('active_path', models.CharField(max_length=128)),
                ('ping_status', models.CharField(default='0% Packet Loss (Hitless)', max_length=64)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('proof_message', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
