frr version 8.4
frr defaults traditional
hostname r3
log syslog informational
ipv6 forwarding
!
interface eth1
 description Link to R5 (BGP)
!
interface eth2
 description Link to S3 (OSPF Area 0)
 ip ospf area 0
 ipv6 ospf6 area 0.0.0.0
!
router ospf
 ospf router-id 10.0.0.3
 default-information originate always
 redistribute bgp metric 10 metric-type 1
 redistribute connected metric 10 metric-type 1
!
router ospf6
 ospf6 router-id 10.0.0.3
 default-information originate always
 redistribute bgp
 redistribute connected
!
router bgp 65001
 bgp router-id 10.0.0.3
 no bgp ebgp-requires-policy
 neighbor 172.16.35.2 remote-as 65005
 neighbor 2001:db8:35::2 remote-as 65005
 !
 address-family ipv4 unicast
  network 10.0.0.0/8
  redistribute ospf
  redistribute connected
  neighbor 172.16.35.2 activate
  no neighbor 2001:db8:35::2 activate
 exit-address-family
 !
 address-family ipv6 unicast
  network 2001:db8::/32
  redistribute ospf6
  redistribute connected
  neighbor 2001:db8:35::2 activate
 exit-address-family
!
line vty
!
