frr version 8.4
frr defaults traditional
hostname r1
log syslog informational
ipv6 forwarding
!
interface eth1
 description OSPF Area 0 uplink to S3
 ip ospf area 0
 ipv6 ospf6 area 0.0.0.0
!
interface eth2.10
 description VLAN 10 Subinterface
!
interface eth2.20
 description VLAN 20 Subinterface
!
router rip
 version 2
 network 10.10.10.0/24
 network 10.10.20.0/24
 redistribute ospf
 redistribute connected
 default-information originate
!
router ripng
 network eth2.10
 network eth2.20
 redistribute ospf6
 redistribute connected
 default-information originate
!
router ospf
 ospf router-id 10.0.0.1
 redistribute rip metric 10 metric-type 1
 redistribute connected metric 10 metric-type 1
!
router ospf6
 ospf6 router-id 10.0.0.1
 redistribute ripng
 redistribute connected
!
line vty
!
